# Generated by Django 3.2.8 on 2021-10-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sales_contact_id',
            new_name='sales_contact',
        ),
    ]
