# Generated by Django 3.2.8 on 2021-10-19 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_auto_20211019_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
