# Generated by Django 3.2.8 on 2021-10-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_sales_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='already_know',
            new_name='already_known',
        ),
    ]
