# Generated by Django 3.2.8 on 2021-10-18 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('attendees', models.IntegerField()),
                ('event_date', models.DateTimeField()),
                ('notes', models.TextField(max_length=500)),
                ('ended', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_assigned_to', to='clients.client')),
                ('support_contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contract_assigned_to', to='clients.client')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_connected_to', to='events.event')),
                ('sales_contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contract_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
