# Generated by Django 3.2.8 on 2021-10-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='client_id',
            new_name='client',
        ),
    ]
