# Generated by Django 3.2.8 on 2021-10-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211018_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
