# Generated by Django 3.2.8 on 2021-10-22 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_delete_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0007_auto_20211022_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contract_assigned_to', to='clients.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_connected_to', to='events.event')),
                ('sales_contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contract_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
