# Generated by Django 3.2.8 on 2021-10-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_sales_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
